# Python Language Basics

This notebook introduces some Python language basics. It is designed for a code-along during the workshop. Some code blocks are deliberately incomplete or have bugs included.

To execute code: Place your cursor in the cell, then hit SHIFT + ENTER

Before we get started... (adapted from David Dempsey's [Python for Geoscientists](https://github.com/ddempsey/python_for_geoscientists) course)

When writing computer code, there are *rules* and there are *conventions*.

- If you break a __\*rule\*__, the code will not work.

- If you break a __\*convention\*__, someone, somewhere puts a mark against your name in a book. At the end of times, there will be a final accounting.

Some Python rules:

- __\*Syntax\*__ - we have very precise expectations about how you write computer code. If you type an opening a bracket, you must close it again later. Some lines must be terminated by a colon, - if you omit this, the code will not work. __\*Learning syntax for a new code is very pedantic and a total pain.\*__ But you have to do it anyway, and at least Python returns readable error messages to help you understand your missteps...
- __\*Indentation\*__ - Python reads indentation (not all languages do) and your code will not work if it is not correctly indented. 

Some Python conventions:

- __\*Commenting\*__ - it is helpful for the poor soul who has to read your poorly written Python (sometimes that is you, weeks or months later) if you have included little 'sign-posts' in the code, articulating what you are doing. These are called comments. They begin with a # symbol, after which you can write whatever you like and it will not be executed as a command.
- __\*Sensible variable names\*__ - relating to the thing the variable represents but not too long. For example, if a variable contains the mean temperature, then Tmean is a sensible variable name, where as the_mean_temperature_of_the_profile or a1 are not sensible variable names. 
- __\*Layout\*__ - Although the computer reads Python line-by-line, using a vertical layout improves the human readability and your ability to comment code. Headings and the liberal use of whitespace improves readbility. 
- __\*Structure\*__ - Python files and projects have a standard structure that improves redabality. The structure of files vary, but all files should start with an explanation of what they do and all packages/modules should be imported at the top. For the advanced folks, more on Python project structure can be found [here](https://docs.python-guide.org/writing/structure/).

Units are a common source of error. Approches to managing this include:
- Include units in the variable names (my preferred) `Tmean_degC = 300`
- Include in-line comments on units and conversions used (good, but can be lost information) `Tmean = 300 # mean temp in degC`
- Consider tools like [Pint](https://pint.readthedocs.io/en/stable/) to manage units, if it is a large problem (good, but assumes everyone knows how to use pint)

---


In [3]:
# Import packages 

''' Good practice: 
Import all libraries/packages used at the top of the document'''

import matplotlib.pyplot as plt # for plotting
import numpy as np # for array based programming
import math # for useful mathematical methods

''' Good practice: 
Packages have standard short names. 
Using the standard name improves readability. 
Look at the docs if you are unsure what the standard name is.
For example, https://matplotlib.org/3.5.3/api/_as_gen/matplotlib.pyplot.html) ''';


In [4]:
# Classic introduction

print('hello world')

hello world


In [5]:
# Basics: "variable"

x = 'hello world'

print(type(x))

# Language basics: "types" (string, integer, float)
# Python is a dynamic typed language, checking type (variable state)

<class 'str'>


Definitions:
- List
- Array
- Tuple
- Dictionary

In [6]:
# Basics: List, array (intro numpy), tuple, dictionary

my_list = [1,2,3,4]
print(type(my_list))

my_array = np.array([1,2,3,4])
print(type(my_array))


<class 'list'>
<class 'numpy.ndarray'>


In [7]:
my_array_of_10s = np.array([10,10,10,10])

new_array = my_array + my_array_of_10s

print(new_array)

# array-based programming

[11 12 13 14]


In [8]:
my_list_of_10s = [10,10,10,10]

new_list = my_list + my_list_of_10s

print(new_list)

[1, 2, 3, 4, 10, 10, 10, 10]


In [9]:
# Basics: "for loop" and whitespace
for value in my_list:
    new_value = value + 10
    print(new_value)

11
12
13
14


In [23]:
# Basics: Complex lists and arrays 

complex_list = ['harry', 1, 9.5, [2,3,4]]
print(complex_list)

complex_array = np.array(['harry', 1, 9.5,[2,3,4]],dtype=object)
print(complex_array, complex_array.shape)

nD_array = np.array([[4,5,6],[1,2,3]])
print(nD_array, nD_array.shape)

# shape tells us the number of elements in each dimension

['harry', 1, 9.5, [2, 3, 4]]
['harry' 1 9.5 list([2, 3, 4])] (4,)
[[4 5 6]
 [1 2 3]] (2, 3)


In [ ]:
# Basics: Python as calculator

In [ ]:
# Basics: Python as plot maker

In [ ]:
# Example: Exploring and understanding equations

In [ ]:
# Functions: re-useable tools

In [2]:
# Pandas: getting data in

In [3]:
# Pandas + Seaborn: make a more complex plot